# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarkMate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarkMate
  pod 'CVCalendar', '~> 1.7.0'

  target 'MarkMateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarkMateUITests' do
    # Pods for testing
  end

end
